# Generated by Django 3.2.2 on 2022-05-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernsme',
            new_name='username',
        ),
    ]
